version: "3.8"

services:
    flask_backend:
      container_name: flask_backend
      build: 
        context: ./backend
        dockerfile: Dockerfile
      ports:
        - "5000:5000"
      volumes:
        - ./backend:/code
      restart: always

    react_frontend:
      container_name: react_frontend
      build: 
        context: ./frontend
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      volumes:
        - ./frontend:/usr/src/app
      restart: always

    mariadb:
      container_name: mariadb
      image: mariadb:latest
      ports:
        - "3306:3306"
      volumes:
        - ./backend/database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: PyBlog
        MYSQL_USER: rijenth
        MYSQL_PASSWORD: rijenth

    phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin/phpmyadmin
      ports:
        - "8080:80"
      restart: always
      environment:
        PMA_HOST: mariadb
        PMA_PORT: 3306
        PMA_USER: rijenth
        PMA_PASSWORD: rijenth